Resolvers
ae-andre/insights-bench pull request #38
Opened 2024-03-15 04:56 UTC by tchan128

_**In progress**_

- Seeded the `userSeeds.json` file by changing files in `seed.js`
- Added query for ALL users
- Added Mutation to add users

Temporary changes to revert: 
- `typeDefs` in type Mutation, removed `Auth` in `addUser` and `login` for now

Success from this update:
- Ability to seed all users 
- Ability to query all users 
- Ability to add user 

![Screenshot 2024-03-15 at 12 55 46 AM](https://github.com/ae-andre/insights-bench/assets/56553374/51c45dad-af6c-47d9-82cd-6240be64219a)

2024-03-15 05:48 UTC, tchan128 commented on server/schemas/typeDefs.js
> +    conversation: Conversation!
`conversation` to match model and since each user should only have ONE conversation, it should not be square bracketed

2024-03-15 05:48 UTC, tchan128 commented on server/schemas/typeDefs.js
> +    _id: ID
Added _id to allow for reference in Comment

2024-03-15 05:48 UTC, tchan128 commented on server/schemas/typeDefs.js
> +    removeUser(userId: ID!): User
For testing purposes.

2024-03-15 07:17 UTC, tchan128 commented
Currently able to query everything, but unable to .populate() user of conversation/comments. Solutions says to change `Conversation` model so that the username field is `String` instead.

2024-03-16 04:42 UTC, Jasmineleeyt approved these changes
Great work!

2024-03-16 06:15 UTC, tchan128 commented
> Great work!

I will probably wait until I figure out displaying the names before merging

2024-03-16 18:26 UTC, kwubbenhorst approved these changes
Yes, everything's here

2024-03-16 19:22 UTC, kwubbenhorst requested changes
I've reviewed your changes to typeDefs. Just a few areas where we differ on the matter of exclamation points.  This was my reasoning:
![Screen Shot 2024-03-16 at 3 01 08 PM](https://github.com/ae-andre/insights-bench/assets/140316693/9c9ead59-b9f8-4644-8a5a-6a6d6c16be4b)
-- conversation on the User model refers to when a user is in a private conversation. This only gets populated if the user starts a private conversation, but the user can participate in a public conversation without needing this field to be filled, so it starts off as null -- should be allowed.
-- _id on the Conversation schema will never be null because it is autogenerated

![Screen Shot 2024-03-16 at 3 01 36 PM](https://github.com/ae-andre/insights-bench/assets/140316693/15759235-e09e-484d-99e9-d8b27e5c1498)
Your version makes listener non-nullable but if we have public conversations too we will not necessarily have a listener assigned to them.

![Screen Shot 2024-03-16 at 3 05 37 PM](https://github.com/ae-andre/insights-bench/assets/140316693/a2a09513-7578-4f98-99fd-68e396675b2d)
I would not make expertise required when adding a user because sharers do not have that field.  In fact I have made their expertise an empty string in the seeds which is not null, but I think it would be okay to take the exclamation point off.
![Screen Shot 2024-03-16 at 3 06 52 PM](https://github.com/ae-andre/insights-bench/assets/140316693/5b38d338-e8c2-41f7-a8f8-76b782cc6110)
You are right that expertise should be a required field when opening any conversation, public or private because this will be needed to categorize a conversation in our list, even for public ones. I will add the exclamation point to mine.

2024-03-16 19:36 UTC, kwubbenhorst approved these changes
Yeah, typeDefs looks like it's 1:1 now.  Do you want me to check over your updates to resolvers before we merge this?

2024-03-16 19:58 UTC, merged